application: pearljam
version: post-ext-v1
runtime: python27
api_version: 1
threadsafe: no

inbound_services:
- xmpp_subscribe

handlers:
- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images

- url: /closure-library
  static_dir: closure-library

- url: /res
  static_dir: res

- url: /views
  static_dir: views

- url: /
  static_files: index.html
  upload: index\.html

- url: /convert
  script: main.app

- url: /listplugins
  script: main.app

- url: /send_blob
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

env_variables:
  WHITELISTED_ORIGINS: 'https?://.*\.google\.com|http://localhost:8082'
